image:
  file: Dockerfile

tasks:
  - init: >
      pip3 install virtualenv &&
      python3 -m virtualenv . &&
      echo 'export PIP_USER=no' >>~/.bash_profile &&
      source ~/.bash_profile &&
      pip install pipenv &&
      pipenv install --dev &&
      pipenv shell

ports:
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore